# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 13:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 4, 1, 13, 11, 52, 871184, tzinfo=utc))),
                ('updated_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='dicercard',
            name='types',
        ),
        migrations.AddField(
            model_name='dicer',
            name='attack_type',
            field=models.CharField(choices=[('MAGIC', 'MAGIC'), ('MELEE', 'MELEE'), ('WHIRLWIND', 'WHIRLWIND'), ('SPEAR', 'SPEAR'), ('BOMBER', 'BOMBER'), ('SNIPER', 'SNIPER')], default='MELEE', max_length=255),
        ),
        migrations.AddField(
            model_name='dicer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 1, 13, 11, 52, 871184, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='dicer',
            name='dice_types',
            field=models.CharField(choices=[('4', '4'), ('44', '44'), ('6', '6'), ('66', '66'), ('10', '10')], default='4', max_length=255),
        ),
        migrations.AddField(
            model_name='dicer',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='dicercard',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 1, 13, 11, 52, 871184, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='dicercard',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='dicercard',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('USER', 'user')], default='USER', max_length=10),
        ),
        migrations.AlterField(
            model_name='dicer',
            name='charge_type',
            field=models.CharField(blank=True, choices=[('BLUE', 'Blue'), ('RED', 'Red')], default='BLUE', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='guild',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Guild'),
        ),
    ]
