# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 13:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170401_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dicer',
            old_name='dice_types',
            new_name='dice_type',
        ),
        migrations.AddField(
            model_name='dicer',
            name='image_full',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dicer',
            name='image_sd',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dicer',
            name='image_thumbnail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dicer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 1, 13, 32, 50, 246272, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dicercard',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 1, 13, 32, 50, 246272, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='guild',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 1, 13, 32, 50, 246272, tzinfo=utc)),
        ),
    ]
