# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 06:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170401_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 2, 6, 10, 50, 326465, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dicercard',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 2, 6, 10, 50, 326465, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='guild',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 2, 6, 10, 50, 326465, tzinfo=utc)),
        ),
    ]
