// auth
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const RECEIVE_AUTH_USER = 'RECEIVE_AUTH_USER'


export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'
export const REMOVE_ALL_NOTIFICATION = 'REMOVE_ALL_NOTIFICATION'

export const SHOW_DIALOG = 'SHOW_DIALOG'
export const HIDE_DIALOG = 'HIDE_DIALOG'


export const SET_CURRENT_MENU = 'SET_CURRENT_MENU'


// lodex
export const RECEIVE_LODEX = 'RECEIVE_LODEX'
